detectors:
  DuplicateMethodCall:
    exclude: 
      - Transactions::DslFile#parse
      - TransactionsManager::Importer#call
  FeatureEnvy:
    exclude:
      - 'CreateClients#change'
      
directories:
  # Your other configuration....
  "app/controllers":
    InstanceVariableAssumption:
      enabled: false
  