Layout/LineLength:
  Exclude:
    - bin/bundle
Metrics/BlockLength:
  Exclude:
    - spec/requests/transactions_request_spec.rb
    - spec/requests/clients_request_spec.rb
Metrics/CyclomaticComplexity:
  Exclude:
    - bin/bundle
Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Exclude:
    - bin/bundle
  