https://increase-transactions.herokuapp.com/file.txt HTTP/1.1
Authorization: Bearer 1234567890qwertyuiopasdfghjklzxcvbnm

###

https://increase-transactions.herokuapp.com/clients/7aae256794aa4f20961e9ccc500f20de HTTP/1.1
Authorization: Bearer 1234567890qwertyuiopasdfghjklzxcvbnm