---
:concurrency: 1
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
 - default
 - transactions
:schedule:
  get_transactions_file:
    cron: '0 2 * * *'
    class: 'GetTransactionsFileJob'
    queue: transactions
    