---
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
 - default
 - transactions
 - process_registry
:schedule:
  get_transactions_file:
    description: Get file.txt with transactions from Increase Transactions API.
    class: 'GetTransactionsFileJob'
    queue: transactions
    every: '10m'
    